// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Envelope } from "./Envelope";

/**
 * One IPC message: a group of events that became visible together.
 */
export type Batch = { session_id: string, events: Array<Envelope>, };
