// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type HandshakeInfo = { 
/**
 * Array of {name, description, argumentHint, aliases}.
 */
commands: JsonValue, 
/**
 * Array of {value, displayName, description, supportedEffortLevels, ...}.
 */
models: JsonValue, account: JsonValue, current_permission_mode: string | null, output_style: string | null, };
