// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type PendingPermission = { request_id: string, tool_name: string, display_name: string | null, description: string | null, input: JsonValue, 
/**
 * `permission_suggestions` passed through verbatim (array or null).
 */
suggestions: JsonValue, tool_use_id: string | null, };
