// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionStatus } from "./SessionStatus";

export type SessionInfo = { id: string, title: string, cwd: string, status: SessionStatus, };
