// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolOutput } from "./ToolOutput";
import type { JsonValue } from "./serde_json/JsonValue";

export type TranscriptItem = { "kind": "UserText", id: string, text: string, 
/**
 * True for CLI-synthesized frames ("[Request interrupted by user]").
 */
injected: boolean, } | { "kind": "AssistantText", id: string, text: string, parent_tool_use_id: string | null, } | { "kind": "Thinking", id: string, text: string, parent_tool_use_id: string | null, } | { "kind": "ToolUse", id: string, name: string, input: JsonValue, 
/**
 * None while the call is executing (or awaiting approval).
 */
output: ToolOutput | null, parent_tool_use_id: string | null, } | { "kind": "CompactMarker", id: string, };
