// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnStats = { turn_cost_usd: number, total_cost_usd: number, duration_ms: bigint | null, is_error: boolean, terminal_reason: string | null, result_text: string | null, };
